services:
  frontend:
    build: ./dev_first
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE: http://service2:5001
    depends_on:
      - service2

  service2:
    build: ./service2
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
